repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml
- repo: local
  hooks:
  -   id: pytest-check
      stages: [pre-commit]
      types: [python]
      name: pytest-check
      entry: python -m pytest
      language: system
      pass_filenames: false
      always_run: true
